
VIEW_LAYER_COLLECTION_PREFIX = 'RL_'
LIGHT_VIEW_LAYER_COLLECTION_PREFIX = 'LS_'

FILE_OUTPUT_PREFIX = 'FileOutput'
RENDER_LAYER_PREFIX = 'RenderLayer'

RENDER_FOLDER = 'renders'

SPACING_X, SPACING_Y = 300, 300

RENDER_TEMPLATE_PATH = '///{folder}/{file_name}'